/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Donate__factory } from "./Donate__factory";
export { MyContract__factory } from "./MyContract__factory";
