/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Donate } from "./Donate";
export type { MyContract } from "./MyContract";
export * as factories from "./factories";
export { Donate__factory } from "./factories/Donate__factory";
export { MyContract__factory } from "./factories/MyContract__factory";
